#!/bin/sh
alias m="mkdir -p -m"
alias cm="chmod -c"
alias scm="sudo chmod -c"
alias co="sudo chown -c"
m 775 unit1exercise4
m 755 unit1exercise4/ausgehaltse
m 775 unit1exercise4/aufkraute
m 775 unit1exercise4/einwarfung
m 775 unit1exercise4/auspflumer
m 775 unit1exercise4/zerwarfte
m 775 unit1exercise4/aufgesitzs
m 775 unit1exercise4/berabarbung
m 775 unit1exercise4/anschmecker
m 775 unit1exercise4/aufkraute/enkletttete
m 775 unit1exercise4/zerwarfte/ausgewarfse
m 775 unit1exercise4/ausgehaltse/ausgekaesung
m 775 unit1exercise4/anschmecker/ansprachtete
m 775 unit1exercise4/berabarbung/zerpflumtete
m 320 unit1exercise4/ausgehaltse/ausgekaesung/ansinnheit
m 2253 unit1exercise4/ausgehaltse/ausgekaesung/zersinnt
m 2150 unit1exercise4/berabarbung/zerpflumtete/eintrittkeit
m 621 unit1exercise4/ausgehaltse/ausgekaesung/verrennst
m 2675 unit1exercise4/zerwarfte/ausgewarfse/aufrabarbt
m 747 unit1exercise4/aufkraute/enkletttete/gekaeser
m 076 unit1exercise4/berabarbung/zerpflumtete/angekatzese
cm 2371 unit1exercise4/ausgehaltse
cm 2413 unit1exercise4/aufkraute
cm 504 unit1exercise4/einwarfung
cm 255 unit1exercise4/auspflumer
cm 2400 unit1exercise4/zerwarfte
cm 003 unit1exercise4/aufgesitzs
cm 2075 unit1exercise4/berabarbung
cm 2574 unit1exercise4/anschmecker
scm 230 unit1exercise4/aufkraute/enkletttete
scm 2725 unit1exercise4/zerwarfte/ausgewarfse
scm 473 unit1exercise4/ausgehaltse/ausgekaesung
scm 764 unit1exercise4/anschmecker/ansprachtete
scm 2526 unit1exercise4/berabarbung/zerpflumtete
co :audio unit1exercise4/ausgehaltse
co :voice unit1exercise4/aufkraute
co :voice unit1exercise4/einwarfung
co :tape unit1exercise4/auspflumer
co :cdrom unit1exercise4/zerwarfte
co :audio unit1exercise4/aufgesitzs
co :voice unit1exercise4/berabarbung
co :student unit1exercise4/anschmecker
co :proxy unit1exercise4/aufkraute/enkletttete
co :floppy unit1exercise4/zerwarfte/ausgewarfse
co :floppy unit1exercise4/ausgehaltse/ausgekaesung
co :student unit1exercise4/anschmecker/ansprachtete
co :proxy unit1exercise4/berabarbung/zerpflumtete
co :news unit1exercise4/ausgehaltse/ausgekaesung/ansinnheit
co :proxy unit1exercise4/ausgehaltse/ausgekaesung/zersinnt
co :cdrom unit1exercise4/berabarbung/zerpflumtete/eintrittkeit
co :audio unit1exercise4/ausgehaltse/ausgekaesung/verrennst
co :audio unit1exercise4/zerwarfte/ausgewarfse/aufrabarbt
co :tape unit1exercise4/aufkraute/enkletttete/gekaeser
co :fax unit1exercise4/berabarbung/zerpflumtete/angekatzese
sudo tar -cvzf unit1-solution4.tgz unit1exercise4
