#!/bin/sh
alias m="mkdir -p -m"
alias cm="chmod -c"
alias scm="sudo chmod -c"
alias co="sudo chown -c"
m 775 unit1exercise3
m 755 unit1exercise3/besinnen
m 775 unit1exercise3/aufrabarbse
m 775 unit1exercise3/angerabarbse
m 775 unit1exercise3/betrittst
m 775 unit1exercise3/anrabarbtete
m 775 unit1exercise3/besprachung
m 775 unit1exercise3/angewitztest
m 775 unit1exercise3/zerrabarbs
m 775 unit1exercise3/besprachung/angekatzete
m 775 unit1exercise3/besinnen/ensitzse
m 775 unit1exercise3/zerrabarbs/getrittung
m 775 unit1exercise3/angerabarbse/aushunden
m 775 unit1exercise3/angewitztest/aufschmeckung
m 615 unit1exercise3/besinnen/ensitzse/gesetzen
m 4033 unit1exercise3/besinnen/ensitzse/enschmeckst
m 532 unit1exercise3/besinnen/ensitzse/ensetzst
m 357 unit1exercise3/zerrabarbs/getrittung/zerrauchheit
m 151 unit1exercise3/angerabarbse/aushunden/aufgegehse
m 4747 unit1exercise3/besprachung/angekatzete/enkrautete
m 4061 unit1exercise3/besprachung/angekatzete/aufkaeste
cm 710 unit1exercise3/besinnen
cm 4013 unit1exercise3/aufrabarbse
cm 077 unit1exercise3/angerabarbse
cm 533 unit1exercise3/betrittst
cm 4753 unit1exercise3/anrabarbtete
cm 446 unit1exercise3/besprachung
cm 350 unit1exercise3/angewitztest
cm 4617 unit1exercise3/zerrabarbs
scm 4211 unit1exercise3/besprachung/angekatzete
scm 175 unit1exercise3/besinnen/ensitzse
scm 4503 unit1exercise3/zerrabarbs/getrittung
scm 364 unit1exercise3/angerabarbse/aushunden
scm 4202 unit1exercise3/angewitztest/aufschmeckung
co lp:cdrom unit1exercise3/besinnen
co nobody:cdrom unit1exercise3/aufrabarbse
co lp:student unit1exercise3/angerabarbse
co lp:fax unit1exercise3/betrittst
co proxy:audio unit1exercise3/anrabarbtete
co news:audio unit1exercise3/besprachung
co mail:cdrom unit1exercise3/angewitztest
co mail:cdrom unit1exercise3/zerrabarbs
co games:uucp unit1exercise3/besprachung/angekatzete
co lp:uucp unit1exercise3/besinnen/ensitzse
co student:audio unit1exercise3/zerrabarbs/getrittung
co uucp:cdrom unit1exercise3/angerabarbse/aushunden
co mail:dip unit1exercise3/angewitztest/aufschmeckung
co proxy:uucp unit1exercise3/besinnen/ensitzse/gesetzen
co uucp:cdrom unit1exercise3/besinnen/ensitzse/enschmeckst
co games:mail unit1exercise3/besinnen/ensitzse/ensetzst
co proxy:uucp unit1exercise3/zerrabarbs/getrittung/zerrauchheit
co mail:mail unit1exercise3/angerabarbse/aushunden/aufgegehse
co mail:floppy unit1exercise3/besprachung/angekatzete/enkrautete
co news:audio unit1exercise3/besprachung/angekatzete/aufkaeste
sudo tar -cvzf unit1-solution3.tgz unit1exercise3
