#!/bin/sh
alias m="mkdir -p -m"
alias c="chmod -c"
alias cs="sudo chmod -c"
alias co="sudo chown -c"
m 775 unit1exercise2
m 755 unit1exercise2/aufgegeht
m 775 unit1exercise2/angetrittte
m 775 unit1exercise2/angehaltung
m 775 unit1exercise2/angesprachs
m 775 unit1exercise2/gefahrte
m 775 unit1exercise2/versetztete
m 775 unit1exercise2/ausgesitztest
m 775 unit1exercise2/angekatzetete
m 775 unit1exercise2/angekatzetete/angehaltst
m 775 unit1exercise2/angehaltung/angewitzkeit
m 775 unit1exercise2/angekatzetete/besinns
m 775 unit1exercise2/angehaltung/ausgewarfst
m 775 unit1exercise2/gefahrte/ausfahrtete
m 675 unit1exercise2/angehaltung/angewitzkeit/einfahren
m 032 unit1exercise2/angekatzetete/angehaltst/verrauchst
m 116 unit1exercise2/angehaltung/angewitzkeit/aufgesinnt
m 641 unit1exercise2/angekatzetete/angehaltst/enwitzkeit
m 572 unit1exercise2/gefahrte/ausfahrtete/ausgetrautest
m 400 unit1exercise2/angekatzetete/besinns/angehunden
m 623 unit1exercise2/angekatzetete/angehaltst/einrauchs
c 351 unit1exercise2/aufgegeht
c 756 unit1exercise2/angetrittte
c 363 unit1exercise2/angehaltung
c 110 unit1exercise2/angesprachs
c 653 unit1exercise2/gefahrte
c 471 unit1exercise2/versetztete
c 134 unit1exercise2/ausgesitztest
c 051 unit1exercise2/angekatzetete
cs 153 unit1exercise2/angekatzetete/angehaltst
cs 621 unit1exercise2/angehaltung/angewitzkeit
cs 044 unit1exercise2/angekatzetete/besinns
cs 630 unit1exercise2/angehaltung/ausgewarfst
cs 057 unit1exercise2/gefahrte/ausfahrtete
co uucp:dip unit1exercise2/aufgegeht
co proxy:tape unit1exercise2/angetrittte
co mail:uucp unit1exercise2/angehaltung
co lp:proxy unit1exercise2/angesprachs
co news:voice unit1exercise2/gefahrte
co mail:uucp unit1exercise2/versetztete
co student:voice unit1exercise2/ausgesitztest
co nobody:fax unit1exercise2/angekatzetete
co news:proxy unit1exercise2/angekatzetete/angehaltst
co student:voice unit1exercise2/angehaltung/angewitzkeit
co nobody:student unit1exercise2/angekatzetete/besinns
co news:tape unit1exercise2/angehaltung/ausgewarfst
co nobody:student unit1exercise2/gefahrte/ausfahrtete
co mail:news unit1exercise2/angehaltung/angewitzkeit/einfahren
co mail:student unit1exercise2/angekatzetete/angehaltst/verrauchst
co games:dip unit1exercise2/angehaltung/angewitzkeit/aufgesinnt
co games:mail unit1exercise2/angekatzetete/angehaltst/enwitzkeit
co proxy:news unit1exercise2/gefahrte/ausfahrtete/ausgetrautest
co lp:tape unit1exercise2/angekatzetete/besinns/angehunden
co mail:news unit1exercise2/angekatzetete/angehaltst/einrauchs
sudo tar -cvzf unit1-solution2.tgz unit1exercise2
