#!/bin/sh
alias m="mkdir -p -m"
alias c="chmod -c"
alias cs="sudo chmod -c"
alias co="sudo chown -c"
m 775 unit1exercise2
m 755 unit1exercise2/verhalttete
m 775 unit1exercise2/austrauheit
m 775 unit1exercise2/angetrauer
m 775 unit1exercise2/aufschmeckst
m 775 unit1exercise2/einfahren
m 775 unit1exercise2/zerrabarbt
m 775 unit1exercise2/ausgerauchkeit
m 775 unit1exercise2/zerkatzete
m 775 unit1exercise2/einfahren/angesinnte
m 775 unit1exercise2/zerrabarbt/einwarft
m 775 unit1exercise2/ausgerauchkeit/aufgeklettkeit
m 775 unit1exercise2/angetrauer/ensetzkeit
m 775 unit1exercise2/aufschmeckst/ausgerauchte
m 544 unit1exercise2/ausgerauchkeit/aufgeklettkeit/gesetzer
m 626 unit1exercise2/zerrabarbt/einwarft/verfahrs
m 646 unit1exercise2/zerrabarbt/einwarft/aufgetritts
m 707 unit1exercise2/angetrauer/ensetzkeit/aufhalttete
m 047 unit1exercise2/einfahren/angesinnte/geklettt
m 520 unit1exercise2/ausgerauchkeit/aufgeklettkeit/einwitzt
m 120 unit1exercise2/einfahren/angesinnte/ausfahrse
c 525 unit1exercise2/verhalttete
c 411 unit1exercise2/austrauheit
c 010 unit1exercise2/angetrauer
c 373 unit1exercise2/aufschmeckst
c 700 unit1exercise2/einfahren
c 566 unit1exercise2/zerrabarbt
c 616 unit1exercise2/ausgerauchkeit
c 023 unit1exercise2/zerkatzete
cs 752 unit1exercise2/einfahren/angesinnte
cs 773 unit1exercise2/zerrabarbt/einwarft
cs 145 unit1exercise2/ausgerauchkeit/aufgeklettkeit
cs 147 unit1exercise2/angetrauer/ensetzkeit
cs 550 unit1exercise2/aufschmeckst/ausgerauchte
co uucp:proxy unit1exercise2/verhalttete
co uucp:mail unit1exercise2/austrauheit
co proxy:uucp unit1exercise2/angetrauer
co uucp:audio unit1exercise2/aufschmeckst
co student:news unit1exercise2/einfahren
co student:audio unit1exercise2/zerrabarbt
co nobody:uucp unit1exercise2/ausgerauchkeit
co nobody:news unit1exercise2/zerkatzete
co uucp:proxy unit1exercise2/einfahren/angesinnte
co lp:uucp unit1exercise2/zerrabarbt/einwarft
co nobody:floppy unit1exercise2/ausgerauchkeit/aufgeklettkeit
co mail:proxy unit1exercise2/angetrauer/ensetzkeit
co proxy:dip unit1exercise2/aufschmeckst/ausgerauchte
co mail:news unit1exercise2/ausgerauchkeit/aufgeklettkeit/gesetzer
co nobody:news unit1exercise2/zerrabarbt/einwarft/verfahrs
co news:news unit1exercise2/zerrabarbt/einwarft/aufgetritts
co news:tape unit1exercise2/angetrauer/ensetzkeit/aufhalttete
co lp:news unit1exercise2/einfahren/angesinnte/geklettt
co proxy:mail unit1exercise2/ausgerauchkeit/aufgeklettkeit/einwitzt
co proxy:tape unit1exercise2/einfahren/angesinnte/ausfahrse
sudo tar -cvzf unit1-solution2.tgz unit1exercise2
